title: my practice repository
author: aayush kumar
email: ayayush@gmail.com
description: you will too much enoughinfo

# social links
twitter_username: sarraayush # DO NOT include the @ character, or else the build will fail!
github_username:  sarraayush # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: mimima
