title: aayush blog
author: aayush kumar
email: aayush@gmail.com
description: > thisblog is temporary  # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username:sarraayush # DO NOT include the @ character, or else the build will fail!
github_username:  sarraayush # DO NOT include the @ character, or else the build will fail!
theme : minima
show_excerpts: false  # set to false to remove excerpts on the homepage
